# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='user.proto',
  package='xituan.user',
  serialized_pb='\n\nuser.proto\x12\x0bxituan.user\"8\n\x10UserLoginRequest\x12\x11\n\tuser_name\x18\x01 \x02(\t\x12\x11\n\tuser_pass\x18\x02 \x02(\t\"\"\n\x11UserLoginResponse\x12\r\n\x05login\x18\x01 \x02(\x08\x32Y\n\x0bUserService\x12J\n\tUserLogin\x12\x1d.xituan.user.UserLoginRequest\x1a\x1e.xituan.user.UserLoginResponseB\x03\x90\x01\x01')




_USERLOGINREQUEST = descriptor.Descriptor(
  name='UserLoginRequest',
  full_name='xituan.user.UserLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_name', full_name='xituan.user.UserLoginRequest.user_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_pass', full_name='xituan.user.UserLoginRequest.user_pass', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=83,
)


_USERLOGINRESPONSE = descriptor.Descriptor(
  name='UserLoginResponse',
  full_name='xituan.user.UserLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='login', full_name='xituan.user.UserLoginResponse.login', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=85,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['UserLoginRequest'] = _USERLOGINREQUEST
DESCRIPTOR.message_types_by_name['UserLoginResponse'] = _USERLOGINRESPONSE

class UserLoginRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGINREQUEST
  
  # @@protoc_insertion_point(class_scope:xituan.user.UserLoginRequest)

class UserLoginResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGINRESPONSE
  
  # @@protoc_insertion_point(class_scope:xituan.user.UserLoginResponse)


_USERSERVICE = descriptor.ServiceDescriptor(
  name='UserService',
  full_name='xituan.user.UserService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=121,
  serialized_end=210,
  methods=[
  descriptor.MethodDescriptor(
    name='UserLogin',
    full_name='xituan.user.UserService.UserLogin',
    index=0,
    containing_service=None,
    input_type=_USERLOGINREQUEST,
    output_type=_USERLOGINRESPONSE,
    options=None,
  ),
])

class UserService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _USERSERVICE
class UserService_Stub(UserService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _USERSERVICE

# @@protoc_insertion_point(module_scope)
